name: bolerplate
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_mobile_ads: ^3.0.0
  app_tracking_transparency: ^2.0.4
  in_app_review: ^2.0.6
  firebase_analytics: ^10.4.1
  firebase_core: ^2.13.0
  flutter_localizations:
    sdk: flutter
  firebase_crashlytics: ^3.3.4
  http: ^0.13.6
  shared_preferences: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSansKR-Black.otf
        - asset: assets/fonts/NotoSansKR-Bold.otf
        - asset: assets/fonts/NotoSansKR-Light.otf
        - asset: assets/fonts/NotoSansKR-Medium.otf
        - asset: assets/fonts/NotoSansKR-Regular.otf
        - asset: assets/fonts/NotoSansKR-Thin.otf
    - family: NotoSerif
      fonts:
        - asset: assets/fonts/NotoSerifKR-Black.otf
        - asset: assets/fonts/NotoSerifKR-Bold.otf
        - asset: assets/fonts/NotoSerifKR-ExtraLight.otf
        - asset: assets/fonts/NotoSerifKR-Light.otf
        - asset: assets/fonts/NotoSerifKR-Medium.otf
        - asset: assets/fonts/NotoSerifKR-Regular.otf
        - asset: assets/fonts/NotoSerifKR-SemiBold.otf
